### ISSUE TITLE
Make fastExpm a package

### ISSUE THREAD

**Issue by alastair-marshall** [fmentink/FastExpm.jl#1]
Hey there,

I was wondering if it would be possible to turn this code into a package that could be registered? Currently for my tests I've just put a copy of the fastExpm.jl file in my directory but it would be simplify installing it if it could be added as a dependency!

Thanks for porting this across because it really is very fast!

**Comment by fmentink** [comment]
Hi Alastair,

I'm quite new to Julia but I'll figure it out. Glad it is useful for you!

Fred

**Comment by alastair-marshall** [comment]
I can also try to put it into a module and submit a pull request if that's helpful?

**Comment by murari0** [comment]
@alastair-marshall I've put the function into its own package. Can you check that it works fine on your end before I look into registering it? The package is in a subfolder right now - we will sort out the folder hierarchy in a bit.

**Comment by alastair-marshall** [comment]
Thanks I'll give it a try!

**Comment by murari0** [comment]
I've submitted the package for addition to the registry. Waiting the required 3 days before it's added. I'll tag a new release once it's up!
