### ISSUE TITLE
[Question] Lower performance when the fastExpm implements on the ComplexF64

### ISSUE THREAD

**Issue by draftman9** [fmentink/FastExpm.jl#3]
I heard that the `fastExpm` could implements matrix exponential with highly performance. However in my case where my matrix is hermitian the `fastExpm()` has lower performance than the built-in `exp`. Here are my codes, results and the ComplexF64 matrix data file `Matrix_data.csv`. May you could help me! 

- Platform: ubuntu 22.04
- Julia version: 1.9.4  installed by juliaup
- Pkg FastExpm.jl version: v1.1.0 installed by julia built-in pkg manager

# Source Codes

```julia
using LinearAlgebra
using DelimitedFiles
using SparseArrays
using FastExpm
using BenchmarkTools

M=readdlm("./Matrix_data.csv", ',', ComplexF64)
M_s = sparse(M)

@btime exp(-1im*(M)*0.5);
@btime fastExpm(-1im*(M_s)*0.5);
@btime fastExpm(-1im*(M)*0.5);
```

# Results

![Screenshot from 2023-12-05 15-59-43](https://github.com/fmentink/FastExpm.jl/assets/99490289/526a0793-4506-4bbd-8a33-e7577275255b)

# Matrix Data File

[Matrix_data.csv](https://github.com/fmentink/FastExpm.jl/files/13556876/Matrix_data.csv)

**Comment by fmentink** [comment]
Hi draftman9,

In that case case the function will not provide benefits. M*0.5 has a large norm and the resulting exponential matrix is not sparse at all. In my test, 68% of the terms are populated. In that case, exp is faster. If you replace 0.5 by 0.01 in your timing, you'll see that fastExpm is about as fast as exp and if it's smaller (e.g 0.01), then it is much faster. I hope this helps.

Fred

**Comment by draftman9** [comment]
> In that case case the function will not provide benefits. M*0.5 has a large norm and the resulting exponential matrix is not sparse at all. In my test, 68% of the terms are populated. In that case, exp is faster. If you replace 0.5 by 0.01 in your timing, you'll see that fastExpm is about as fast as exp and if it's smaller (e.g 0.01), then it is much faster. I hope this helps.

Thanks for your reply~

Sounds like the performance is related to how sparse the result is, right? A little weird. If so, is the performance limited by the progress of building the resulting exponential density matrix? In my case, if I decrease the `dt`, the benefits provided by the `fastExpm` can not counterbalance the lost efficiency from the smaller `dt`, which troubles me... 

By the way. What I really want to implement is the evolution of time-dependent Schrödinger equation (TDSE).

$$
\ket{\psi(t+\Delta t)}  = e^{-iH(t)\Delta t /\hbar} \ket{\psi(t)}  
$$

**Comment by fmentink** [comment]
This is not weird, this how the function works (you can look at the code and the reference I cited).
When the matrix size if large, it relies on the fact that the matrix remains sparse to ensure its speed. There is not benefit in Taylor expansion if the matrix is not sparse. 
For your problem, I do not know how quickly your Hamiltonian changes with time. Is it very slow and you need large time steps? Often your Hamiltonian changes quickly and you need small time steps.
You could also use https://en.wikipedia.org/wiki/Exponentiation_by_squaring
I think expmv may more be appropriate for your state propagation https://github.com/higham/expmv.

**Comment by draftman9** [comment]
>  You could also use https://en.wikipedia.org/wiki/Exponentiation_by_squaring I think expmv may more be appropriate for your state propagation https://github.com/higham/expmv.

Thanks a lot! These materials help me a lot!
